# Generated by Django 3.1.2 on 2020-10-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservideoitem',
            options={},
        ),
        migrations.AlterField(
            model_name='uservideoitem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='uservideoitem',
            unique_together={('user', 'imdb_id')},
        ),
    ]
