# Generated by Django 3.1.2 on 2020-10-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201010_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoitem',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=10),
        ),
    ]
